### ISSUE TITLE
higher maxDaysToShow results in events beeing lost

### ISSUE THREAD

**Issue by itobey** [marksie1988/atomic-calendar-revive#458] opened 2021-07-14 13:21 UTC
Hi, I want my dashboard in Home Assistant to show the next 3 events. So I limit the count `maxEventCount: 3`. If I set `maxDaysToShow: 7` and there are only 2 events in that range - but I want to always display 3 - the logical thing is to just increase it to: `maxDaysToShow: 30`. If I do that, then events that are already in the next days get lost and some other events are shown. It seems to be not chronological.

Another example:
Today (14.7.) I have the following events:
15.7.: 2 events
16.7.: 1 event
19.7.: 1 event

When using `maxDaysToShow: 7` with 3 events only one of the events on 15.7. is shown (and the next 2). But when I limit `maxDaysToShow: 5` it shows the 2 events of 15.7. and the one on 16.7.  So I'm very positive that this is a sorting issue. 

See screenshots for the visuals.

## Expected behaviour
The events should always be retrieved and shown in chronological order.

## Current behaviour
Some events get lost when increasing the amount of days to look ahead.

## Screenshot

![image](https://user-images.githubusercontent.com/22119845/125627932-1fd0efbd-ad77-4708-954d-44bb74436d3a.png)

![image](https://user-images.githubusercontent.com/22119845/125628049-147c1ebf-06d2-4d45-a729-33b375e95839.png)

## Possible reasons and solutions
I guess it's a chronological issue.

## Steps to reproduce
Have some events, display only 3 events and increase the amount of days.

## Context
I'm losing data which is annoying.

## Custom values
```
  - type: custom:atomic-calendar-revive
    entities:
      - entity: calendar.default_calendar
    firstDayOfWeek: 1
    maxDaysToShow: 7
    name: Events
    showDate: true
    sortByStartTime: false
    showLocation: false
    showDeclined: false
    showLoader: false
    hideFinishedEvents: false
    showRelativeTime: false
    dateFormat: LL
    showCurrentEventLine: false
    showProgressBar: false
    showWeekDay: true
    showMonth: false
    showDescription: false
    disableEventLink: false
    showNoEventsForToday: false
    showEventIcon: false
    disableLocationLink: false
    showFullDayProgress: false
    showHiddenText: false
    calShowDescription: false
    showLastCalendarWeek: false
    disableCalEventLink: false
    disableCalLocationLink: false
    disableCalLink: true
    dimFinishedEvents: true
    cardHeight: 100%
    maxEventCount: 3
```

## Your environment
Home Assistant Docker Image: homeassistant/home-assistant:2021.6.6
HACS: 1.13.2
Atomic Calender Revive: v4.5.0
The Calendar I'm using is a CalDAV selfhosted: Baikal

## Stack trace / logging
-

## Checklist

- [X] I searched the current issues and the issue is not known.
- [X] I searched the troubleshooting and there's no fix available for this bug.
- [X] I searched on Google, YouTube, Reddit and there's no fix.
- [X] I am mostly sure that the problem is related to the code and isn't my fault.

**Comment by marksie1988** [comment] 2021-07-21 13:45
Thanks for all the information, I will need to test and see what is happening here. 

The calendar will now sort all events in date order and then do any filtering so it is interesting that this is happening.

**Comment by itobey** [comment] 2021-07-21 17:52
Then it is indeed a strange behavior for me. I'll be glad to help, if I can do anything or verify further investigations, just give me a message.

**Comment by marksie1988** [comment] 2021-09-20 10:00
Hi there, 

I have just taken a look and was unable to reproduce this issue. I have setup test events the same as the examples you sent here, then set the max days and max events, every time it shows 3 events in the correct order.

**Comment by goldbowler** [comment] 2021-09-26 07:42
I have the same issue. Events are lost when filter is applied. Also yesterdays whole days events sometimes shows up day after but greyed out.

**Comment by marksie1988** [comment] 2021-09-26 07:53
@goldbowler  please could you provide an example of the events and what is not being shown correctly? 

I was unable to reproduce the scenario based on the above information. Could you also supply your config I will then recreate the events in my calendar along with your config to see if I can reproduce the issue.

**Comment by marksie1988** [comment] 2021-10-19 20:30
as there has been no update im closing this one out.

**Closed by marksie1988** 2021-10-19 20:30 UTC
Labels: type/bug
