### ISSUE TITLE
[BUG] Repeated Calendar Entries not showing on Month View

### ISSUE THREAD

**Issue by dac21** [marksie1988/atomic-calendar-revive#90] opened 2020-05-09 18:33 UTC
For an event which repeats, it only appears on the monthly view on the first day.

**Comment by marksie1988** [comment] 2020-05-10 15:03
Please make sure you fill out the bug template, unfortunately this description doesn't provide enough info for me to know what the issue is properly. Please full out the below, do you mean events that are over multiple days or events that repeat say once a week? 

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Setup Information (please complete the following information):**
 - Plugin Version
 - Browser & Version [e.g. chrome, safari, chrome mobile etc.]

**Additional context**
Add any other context about the problem here.

**Comment by marksie1988** [comment] 2020-05-17 14:01
closing as OP hasnt updated the issue

**Closed by marksie1988** 2020-05-17 14:01 UTC
Labels: bug

**Comment by honkerst** [comment] 2020-05-18 02:09
I'm seeing this behaviour as well. 

Describe the bug
Events that repeat daily only appear on the first day of the calendar. 

To Reproduce
Add some events that repeat daily. 

Expected behavior
I expect to see the events listed on every day of the month. 

In the screenshot below are both calendars are showing the same google calendar. The calendar only contains 5 events which repeat every day. However there is only an icon on the first day of the month. Clicking the first day (27 April) shows the day's events. Clicking any of the other days does nothing. 

Screenshots
<img width="423" alt="Screenshot 2020-05-18 at 03 04 52" src="https://user-images.githubusercontent.com/43205559/82167703-87512a00-98b4-11ea-83c4-36f4b07feea2.png">


Setup Information (please complete the following information):

Plugin Version 
1.4.2

Browser & Version 
Chrome 81.0.4044.138
Opera 68.0.3618.104

Additional context
This also affects the List view, where you only see the repeating events for 1 day, no matter what maxDaysToShow or maxEventCount are set to.
